name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutterflow_ui: ^0.2.0+1
  url_launcher: ^6.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true